name: Java Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build and Run Java Script
        run: |
          javac .github/scripts/GitHubActionsExample.java
          java .github/scripts/GitHubActionsExample
